
namespace EXBP.Dipren
{
    /// <summary>
    ///   Enumerates node types.
    /// </summary>
    public enum NodeType
    {
        /// <summary>
        ///   The event was generated by the <see cref="Dipren.Scheduler"/> type.
        /// </summary>
        Scheduler,

        /// <summary>
        ///   The event was generated by the <see cref="Dipren.Engine"/> type.
        /// </summary>
        Engine
    }
}
