//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXBP.Dipren.Demo.Postgres.Commands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DeployQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeployQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EXBP.Dipren.Demo.Postgres.Commands.DeployQueries", typeof(DeployQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE SCHEMA &quot;demo&quot;;
        ///
        ///CREATE TABLE &quot;demo&quot;.&quot;cuboids&quot;
        ///(
        ///  &quot;id&quot; UUID NOT NULL,
        ///  &quot;width&quot; INT NOT NULL,
        ///  &quot;height&quot; INT NOT NULL,
        ///  &quot;depth&quot; INT NOT NULL,
        ///
        ///  CONSTRAINT &quot;pk_cuboids&quot; PRIMARY KEY (&quot;id&quot;)
        ///);
        ///
        ///CREATE TABLE &quot;demo&quot;.&quot;volumes&quot;
        ///(
        ///  &quot;id&quot; UUID NOT NULL,
        ///  &quot;volume&quot; INT NOT NULL,
        ///
        ///  CONSTRAINT &quot;pk_volumes&quot; PRIMARY KEY (&quot;id&quot;)
        ///);.
        /// </summary>
        internal static string CreateDemoDatabaseSchema {
            get {
                return ResourceManager.GetString("CreateDemoDatabaseSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE SCHEMA &quot;dipren&quot;;
        ///
        ///COMMENT ON SCHEMA &quot;dipren&quot; IS &apos;Defines the Dipren database objects&apos;;
        ///
        ///
        ///CREATE TABLE &quot;dipren&quot;.&quot;jobs&quot;
        ///(
        ///  &quot;id&quot; VARCHAR(256) NOT NULL,
        ///  &quot;created&quot; TIMESTAMP NOT NULL,
        ///  &quot;updated&quot; TIMESTAMP NOT NULL,
        ///  &quot;batch_size&quot; INTEGER NOT NULL,
        ///  &quot;timeout&quot; BIGINT NOT NULL,
        ///  &quot;clock_drift&quot; BIGINT NOT NULL,
        ///  &quot;started&quot; TIMESTAMP NULL,
        ///  &quot;completed&quot; TIMESTAMP NULL,
        ///  &quot;state&quot; INTEGER NOT NULL,
        ///  &quot;error&quot; TEXT NULL,
        ///  
        ///  CONSTRAINT &quot;pk_jobs&quot; PRIMARY KEY (&quot;id&quot;)
        ///);
        ///
        ///COMMENT ON COLUMN &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateDiprenDatabaseSchema {
            get {
                return ResourceManager.GetString("CreateDiprenDatabaseSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP SCHEMA IF EXISTS &quot;demo&quot; CASCADE;.
        /// </summary>
        internal static string DropDemoDatabaseSchema {
            get {
                return ResourceManager.GetString("DropDemoDatabaseSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP SCHEMA IF EXISTS &quot;dipren&quot; CASCADE;.
        /// </summary>
        internal static string DropDiprenDatabaseSchema {
            get {
                return ResourceManager.GetString("DropDiprenDatabaseSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO
        ///  &quot;demo&quot;.&quot;cuboids&quot;
        ///SELECT
        ///  gen_random_uuid() AS &quot;id&quot;,
        ///  floor(random() * (100 - 1 + 1)) + 1 AS &quot;width&quot;,
        ///  floor(random() * (100 - 1 + 1)) + 1 AS &quot;height&quot;,
        ///  floor(random() * (100 - 1 + 1)) + 1 AS &quot;depth&quot;
        ///FROM
        ///  generate_series(1, @limit);.
        /// </summary>
        internal static string GenerateCuboids {
            get {
                return ResourceManager.GetString("GenerateCuboids", resourceCulture);
            }
        }
    }
}
