//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXBP.Dipren.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EngineDataStoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EngineDataStoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EXBP.Dipren.Data.EngineDataStoreResources", typeof(EngineDataStoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A job with the specified unique identifier already exists in the data store..
        /// </summary>
        internal static string JobWithSameIdentiferAlreadyExists {
            get {
                return ResourceManager.GetString("JobWithSameIdentiferAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A job with the specified unique identifier does not exist in the data store..
        /// </summary>
        internal static string JobWithSpecifiedIdentifierDoesNotExist {
            get {
                return ResourceManager.GetString("JobWithSpecifiedIdentifierDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lock on the specified partition is no longer held..
        /// </summary>
        internal static string PartitionLockNoLongerHeld {
            get {
                return ResourceManager.GetString("PartitionLockNoLongerHeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A partition with the specified unique identifier already exists in the data store..
        /// </summary>
        internal static string PartitionWithSameIdentifierAlreadyExists {
            get {
                return ResourceManager.GetString("PartitionWithSameIdentifierAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A partition with the specified unique identifier does not exist in the data store..
        /// </summary>
        internal static string PartitionWithSpecifiedIdentifierDoesNotExist {
            get {
                return ResourceManager.GetString("PartitionWithSpecifiedIdentifierDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job referenced by the partition does not exist within the data store..
        /// </summary>
        internal static string ReferencedJobDoesNotExist {
            get {
                return ResourceManager.GetString("ReferencedJobDoesNotExist", resourceCulture);
            }
        }
    }
}
