//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXBP.Dipren.Diagnostics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AssertResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssertResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EXBP.Dipren.Diagnostics.AssertResources", typeof(AssertResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified collection is empty..
        /// </summary>
        internal static string MessageCollectionIsEmpty {
            get {
                return ResourceManager.GetString("MessageCollectionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified comparand is null..
        /// </summary>
        internal static string MessageComparandIsNull {
            get {
                return ResourceManager.GetString("MessageComparandIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified date-time value is not in local time..
        /// </summary>
        internal static string MessageDateTimeNotLocal {
            get {
                return ResourceManager.GetString("MessageDateTimeNotLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified date-time value is not in UTC time..
        /// </summary>
        internal static string MessageDateTimeNotUtc {
            get {
                return ResourceManager.GetString("MessageDateTimeNotUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified GUID value is empty..
        /// </summary>
        internal static string MessageGuidIsEmpty {
            get {
                return ResourceManager.GetString("MessageGuidIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified string value is empty..
        /// </summary>
        internal static string MessageStringIsEmpty {
            get {
                return ResourceManager.GetString("MessageStringIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified type is not an enumeration..
        /// </summary>
        internal static string MessageTypeIsNotEnum {
            get {
                return ResourceManager.GetString("MessageTypeIsNotEnum", resourceCulture);
            }
        }
    }
}
