
namespace EXBP.Dipren.Diagnostics
{
    /// <summary>
    ///   Enumerates the sources that can generate events.
    /// </summary>
    public enum EventSource
    {
        /// <summary>
        ///   The event was generated by the <see cref="EXBP.Dipren.Scheduler"/> type.
        /// </summary>
        Scheduler,

        /// <summary>
        ///   The event was generated by the <see cref="EXBP.Dipren.Engine"/> type.
        /// </summary>
        Engine
    }
}
