//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXBP.Dipren.Demo.SQLite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MeasurementDataSourceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MeasurementDataSourceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EXBP.Dipren.Demo.SQLite.MeasurementDataSourceResources", typeof(MeasurementDataSourceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///  COUNT() AS &quot;count&quot;
        ///FROM
        ///  &quot;measurements&quot;
        ///WHERE
        ///  (&quot;id&quot; &gt;= $first) AND
        ///  ((($inclusive = 1) AND (&quot;id&quot; &lt;= $last)) OR (($inclusive = 0) AND (&quot;id&quot; &lt; $last)));.
        /// </summary>
        internal static string QueryEstimateRangeSize {
            get {
                return ResourceManager.GetString("QueryEstimateRangeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///  MIN(&quot;id&quot;) AS &quot;first&quot;,
        ///  MAX(&quot;id&quot;) AS &quot;last&quot;
        ///FROM
        ///  &quot;measurements&quot;;.
        /// </summary>
        internal static string QueryGetEntireRangeAscending {
            get {
                return ResourceManager.GetString("QueryGetEntireRangeAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///  &quot;id&quot;,
        ///  &quot;width&quot;,
        ///  &quot;height&quot;,
        ///  &quot;depth&quot;
        ///FROM
        ///  &quot;measurements&quot;
        ///WHERE
        ///  (&quot;id&quot; &gt;= $first) AND
        ///  ((($inclusive = 1) AND (&quot;id&quot; &lt;= $last)) OR (($inclusive = 0) AND (&quot;id&quot; &lt; $last)))
        ///ORDER BY
        ///  &quot;id&quot;
        ///LIMIT
        ///  $skip,
        ///  $take;.
        /// </summary>
        internal static string QueryGetNextBatchAscending {
            get {
                return ResourceManager.GetString("QueryGetNextBatchAscending", resourceCulture);
            }
        }
    }
}
