//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXBP.Dipren.Demo.SQLite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SourceDatabaseResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SourceDatabaseResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EXBP.Dipren.Demo.SQLite.SourceDatabaseResources", typeof(SourceDatabaseResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;measurements&quot;
        ///(
        ///  &quot;id&quot; INTEGER NOT NULL,
        ///  &quot;width&quot; INTEGER NOT NULL,
        ///  &quot;height&quot; INTEGER NOT NULL,
        ///  &quot;depth&quot; INTEGER NOT NULL,
        ///
        ///  CONSTRAINT &quot;pk_measurements&quot; PRIMARY KEY (&quot;id&quot;)
        ///);.
        /// </summary>
        internal static string QueryCreateTableMeasurements {
            get {
                return ResourceManager.GetString("QueryCreateTableMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO &quot;measurements&quot;
        ///(
        ///  &quot;id&quot;,
        ///  &quot;width&quot;,
        ///  &quot;height&quot;,
        ///  &quot;depth&quot;
        ///)
        ///VALUES
        ///(
        ///  $id,
        ///  $width,
        ///  $height,
        ///  $depth
        ///);.
        /// </summary>
        internal static string QueryInsertMeasurement {
            get {
                return ResourceManager.GetString("QueryInsertMeasurement", resourceCulture);
            }
        }
    }
}
