//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXBP.Dipren.Telemetry {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OpenTelemetryEngineMetricsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OpenTelemetryEngineMetricsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EXBP.Dipren.Telemetry.OpenTelemetryEngineMetricsResources", typeof(OpenTelemetryEngineMetricsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of batches processed..
        /// </summary>
        internal static string InstrumentDescriptionBatchesCompleted {
            get {
                return ResourceManager.GetString("InstrumentDescriptionBatchesCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of batches retrieved from the data source..
        /// </summary>
        internal static string InstrumentDescriptionBatchesRetrieved {
            get {
                return ResourceManager.GetString("InstrumentDescriptionBatchesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duration of processing a batch..
        /// </summary>
        internal static string InstrumentDescriptionBatchProcessingDuration {
            get {
                return ResourceManager.GetString("InstrumentDescriptionBatchProcessingDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duration of retrieving a batch of items from the data source..
        /// </summary>
        internal static string InstrumentDescriptionBatchRetrievalDuration {
            get {
                return ResourceManager.GetString("InstrumentDescriptionBatchRetrievalDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of engines in various states..
        /// </summary>
        internal static string InstrumentDescriptionEngines {
            get {
                return ResourceManager.GetString("InstrumentDescriptionEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duration of checking if a split request is pending..
        /// </summary>
        internal static string InstrumentDescriptionIsSplitRequestPendingDuration {
            get {
                return ResourceManager.GetString("InstrumentDescriptionIsSplitRequestPendingDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of keys completed..
        /// </summary>
        internal static string InstrumentDescriptionKeysCompleted {
            get {
                return ResourceManager.GetString("InstrumentDescriptionKeysCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of keys retrieved from the data source..
        /// </summary>
        internal static string InstrumentDescriptionKeysRetrieved {
            get {
                return ResourceManager.GetString("InstrumentDescriptionKeysRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of partitions completed..
        /// </summary>
        internal static string InstrumentDescriptionPartitionsCompleted {
            get {
                return ResourceManager.GetString("InstrumentDescriptionPartitionsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of partitions created..
        /// </summary>
        internal static string InstrumentDescriptionPartitionsCreated {
            get {
                return ResourceManager.GetString("InstrumentDescriptionPartitionsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duration of reporting progress..
        /// </summary>
        internal static string InstrumentDescriptionReportProgressDuration {
            get {
                return ResourceManager.GetString("InstrumentDescriptionReportProgressDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duration of attempting to acqurie a partition..
        /// </summary>
        internal static string InstrumentDescriptionTryAcquirePartitionDuration {
            get {
                return ResourceManager.GetString("InstrumentDescriptionTryAcquirePartitionDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duration of attempting to request a partition to be split..
        /// </summary>
        internal static string InstrumentDescriptionTryRequestSplitDuration {
            get {
                return ResourceManager.GetString("InstrumentDescriptionTryRequestSplitDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to batches.
        /// </summary>
        internal static string UnitBatches {
            get {
                return ResourceManager.GetString("UnitBatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to engines.
        /// </summary>
        internal static string UnitEngines {
            get {
                return ResourceManager.GetString("UnitEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keys.
        /// </summary>
        internal static string UnitKeys {
            get {
                return ResourceManager.GetString("UnitKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliseconds.
        /// </summary>
        internal static string UnitMilliseconds {
            get {
                return ResourceManager.GetString("UnitMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partitions.
        /// </summary>
        internal static string UnitPartitions {
            get {
                return ResourceManager.GetString("UnitPartitions", resourceCulture);
            }
        }
    }
}
