name: Publish Dipren

on:
  push:
    tags:
      - 'v*'

env:
  SOURCE_DIRECTORY: './source/EXBP.Dipren'
  PACKAGE_DIRECTORY: ${{github.workspace}}/output
  PACKAGE_GALLERY: 'https://api.nuget.org/v3/index.json'

jobs:
  Publish:

    runs-on: ubuntu-latest

    steps:
    - name: 'Check-out'
      uses: actions/checkout@v3

    - name: 'Setup .NET 6.0'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: 'Restore dependencies'
      run: dotnet restore ${{env.SOURCE_DIRECTORY}}

    - name: 'Build solution'
      run: dotnet build --configuration Release --no-restore ${{env.SOURCE_DIRECTORY}}

    - name: 'Set version'
      id: verion
      uses: battila7/get-version-action@v2

    - name: 'Create Package'
      run: dotnet pack ${{env.SOURCE_DIRECTORY}} --configuration Release --no-restore --no-build -p:PackageVersion=${{steps.version.outputs.version-without-v}} --output ${{env.PACKAGE_DIRECTORY}}

    - name: 'Publish Package'
      run: dotnet nuget push ${{env.PACKAGE_DIRECTORY}}/*.nupkg ${{env.PACKAGE_DIRECTORY}}/*.snupkg --source ${{env.PACKAGE_GALLERY}} --api-key ${{secrets.NUGET_DIPREN_TOKEN}}